name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          # Ensure dist directory exists and copy 404.html
          mkdir -p dist
          cp ./client/public/404.html ./dist/
          # Create .nojekyll file to prevent Jekyll processing
          touch ./dist/.nojekyll
        env:
          VITE_BASE_URL: /repliNostr/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true # Clean up gh-pages branch