name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Clean up public directory if it exists
          rm -rf public
          # Export environment variables for build
          export VITE_BASE_URL="/repliNostr/"
          export VITE_ASSET_URL="/repliNostr/"
          export BASE_URL="/repliNostr/"
          export BASE="/repliNostr/"
          # Build the project
          npm run build
          # Create public directory and copy build output
          mkdir -p public
          cp -r dist/public/* public/
          # Copy 404.html
          cp ./client/public/404.html ./public/
          # Create .nojekyll file to prevent Jekyll processing
          touch ./public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true # Clean up gh-pages branch