name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          # Clean up public directory if it exists
          rm -rf public
          # Build the project
          npm run build
          # Ensure public directory exists and copy 404.html
          mkdir -p public
          cp ./client/public/404.html ./public/
          # Create .nojekyll file to prevent Jekyll processing
          touch ./public/.nojekyll
          # Copy build output to public directory
          cp -r ./dist/public/* ./public/
        env:
          VITE_BASE_URL: /repliNostr/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true # Clean up gh-pages branch